### ISSUE TITLE
Brackets 1.11 -- Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.

### ISSUE THREAD

**Issue by dan-willett** [myaghobi/Brackets-QuickFormTool#10]
Getting the following warning:

Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at quickFormToolProvider (file:///C:/../AppData/Roaming/Brackets/extensions/user/m.yaghobi.quickformtool/main.js:25:30)
    at Object.<anonymous> (file:///C:/../AppData/Roaming/Brackets/extensions/user/m.yaghobi.quickformtool/main.js:60:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)

**Comment by myaghobi** [comment]
@dan-willett thanks for your feedback.
I have checked your issue and I got no any warning on Brackets 1.11(release 86b5e2d4e)! But I done a commit(a0b4f90c8723f4b3802f98e7fdf4c708df3e8f22) to resolve it according to your warning!
